api_version: 1
runtime: nodejs
env: flex
env_variables:
  API_KEY: ''
  RECAPTCHA_SITE_KEY: ''
  RECAPTCHA_SECRET_KEY: ''
  IMAGE_BASE_URL: ''
instance_class: F1
automatic_scaling:
  min_idle_instances: 0
